package fr.uga.iut2.genconf.vue;

import java.awt.CardLayout;
import javax.swing.JPanel;


public class VuePrincipale extends javax.swing.JFrame {
    private final GUI gui;

    /**
     * Creates new form VuePrincipale
     */
    public VuePrincipale(GUI gui) {
        this.gui = gui;

        // création de l'interface générée
        this.initComponents();
    }

    protected void afficher() {
        this.setSize(600,400);
        this.setVisible(true);
    }

    protected void ajouterVue(JPanel vue, String id) {

        CardLayout cLayout = (CardLayout) this.getContentPane().getLayout();

        cLayout.addLayoutComponent(vue, id);
        this.add(vue);
    }

    protected void afficherVue(String id) {
        CardLayout cLayout = (CardLayout) getContentPane().getLayout();
        cLayout.show(this.getContentPane(), id);
    }

    protected void fermer() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GenConf");
        getContentPane().setLayout(new java.awt.CardLayout());

        jMenu1.setText("Gestion");

        jMenuItem1.setText("Créer une conférence");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuCreationConference(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Créer un utilisateur");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuCreationUtilisateur(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator2);

        jMenuItem4.setText("Quitter");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuQuitter(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionMenuCreationUtilisateur(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuCreationUtilisateur
        this.gui.actionCreerUtilisateur();
    }//GEN-LAST:event_actionMenuCreationUtilisateur

    private void actionMenuCreationConference(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuCreationConference
        this.gui.actionCreerConference();
    }//GEN-LAST:event_actionMenuCreationConference

    private void actionMenuQuitter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuQuitter
        this.gui.actionTerminer();
    }//GEN-LAST:event_actionMenuQuitter

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
